ids = ['restaurants_restaurant_R_res_id', 'restaurants_restaurant_apikey', 'restaurants_restaurant_id',
       'restaurants_restaurant_name', 'restaurants_restaurant_url', 'restaurants_restaurant_location_address',
       'restaurants_restaurant_location_locality', 'restaurants_restaurant_location_city', 'restaurants_restaurant_location_city_id',
       'restaurants_restaurant_location_latitude', 'restaurants_restaurant_location_longitude', 'restaurants_restaurant_location_zipcode',
       'restaurants_restaurant_location_country_id', 'restaurants_restaurant_location_locality_verbose',
       'restaurants_restaurant_switch_to_order_menu', 'restaurants_restaurant_cuisines', 'restaurants_restaurant_average_cost_for_two',
       'restaurants_restaurant_price_range', 'restaurants_restaurant_currency', 'restaurants_restaurant_thumb',
       'restaurants_restaurant_user_rating_aggregate_rating', 'restaurants_restaurant_user_rating_rating_text',
       'restaurants_restaurant_user_rating_rating_color', 'restaurants_restaurant_user_rating_votes', 'restaurants_restaurant_photos_url',
       'restaurants_restaurant_menu_url', 'restaurants_restaurant_featured_image', 'restaurants_restaurant_has_online_delivery',
       'restaurants_restaurant_is_delivering_now', 'restaurants_restaurant_deeplink', 'restaurants_restaurant_has_table_booking', 'restaurants_restaurant_events_url']

restaurants={    
'restaurants_0_restaurant_R_res_id': 16668008,
    'restaurants_0_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_0_restaurant_id': '16668008',
    'restaurants_0_restaurant_name': 'Arigato Sushi',
    'restaurants_0_restaurant_url': 'https://www.zomato.com/yorkton-sk/arigato-sushi-yorkton?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_0_restaurant_location_address': '14 Second Ave North, Yorkton, SK S3N 1G1',
    'restaurants_0_restaurant_location_locality': 'Yorkton',
    'restaurants_0_restaurant_location_city': 'Yorkton',
    'restaurants_0_restaurant_location_city_id': 3600,
    'restaurants_0_restaurant_location_latitude': '51.2106824000',
    'restaurants_0_restaurant_location_longitude': '-102.4613173000',
    'restaurants_0_restaurant_location_zipcode': 'S3N 1G1',
    'restaurants_0_restaurant_location_country_id': 37,
    'restaurants_0_restaurant_location_locality_verbose': 'Yorkton, Yorkton',
    'restaurants_0_restaurant_switch_to_order_menu': 0,
    'restaurants_0_restaurant_cuisines': 'Asian',
    'restaurants_0_restaurant_average_cost_for_two': 25,
    'restaurants_0_restaurant_price_range': 2,
    'restaurants_0_restaurant_currency': '$',
    'restaurants_0_restaurant_thumb': '',
    'restaurants_0_restaurant_user_rating_aggregate_rating': '3.3',
    'restaurants_0_restaurant_user_rating_rating_text': 'Average',
    'restaurants_0_restaurant_user_rating_rating_color': 'CDD614',
    'restaurants_0_restaurant_user_rating_votes': '26',
    'restaurants_0_restaurant_photos_url': 'https://www.zomato.com/yorkton-sk/arigato-sushi-yorkton/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_0_restaurant_menu_url': 'https://www.zomato.com/yorkton-sk/arigato-sushi-yorkton/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_0_restaurant_featured_image': '',
    'restaurants_0_restaurant_has_online_delivery': 0,
    'restaurants_0_restaurant_is_delivering_now': 0,
    'restaurants_0_restaurant_deeplink': 'zomato://restaurant/16668008',
    'restaurants_0_restaurant_has_table_booking': 0,
    'restaurants_0_restaurant_events_url': 'https://www.zomato.com/yorkton-sk/arigato-sushi-yorkton/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_1_restaurant_R_res_id': 801690,
    'restaurants_1_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_1_restaurant_id': '801690',
    'restaurants_1_restaurant_name': 'Mocha',
    'restaurants_1_restaurant_url': 'https://www.zomato.com/lucknow/mocha-gomti-nagar?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_1_restaurant_location_address': 'CP-1, 2nd Floor, Anand Plaza, Viram Khand-1, Near Patrakarpuram Crossing, Gomti Nagar, Lucknow',
    'restaurants_1_restaurant_location_locality': 'Gomti Nagar',
    'restaurants_1_restaurant_location_city': 'Lucknow',
    'restaurants_1_restaurant_location_city_id': 8,
    'restaurants_1_restaurant_location_latitude': '26.8528099000',
    'restaurants_1_restaurant_location_longitude': '81.0011849000',
    'restaurants_1_restaurant_location_zipcode': '226010',
    'restaurants_1_restaurant_location_country_id': 1,
    'restaurants_1_restaurant_location_locality_verbose': 'Gomti Nagar, Lucknow',
    'restaurants_1_restaurant_switch_to_order_menu': 0,
    'restaurants_1_restaurant_cuisines': 'Cafe, Italian, Continental',
    'restaurants_1_restaurant_average_cost_for_two': 800,
    'restaurants_1_restaurant_price_range': 3,
    'restaurants_1_restaurant_currency': 'Rs.',
    'restaurants_1_restaurant_thumb': 'https://b.zmtcdn.com/data/pictures/0/801690/fa778a9be95f95e7d9846e23b59c8d1a_featured_v2.jpg',
    'restaurants_1_restaurant_user_rating_aggregate_rating': '4.6',
    'restaurants_1_restaurant_user_rating_rating_text': 'Excellent',
    'restaurants_1_restaurant_user_rating_rating_color': '3F7E00',
    'restaurants_1_restaurant_user_rating_votes': '567',
    'restaurants_1_restaurant_photos_url': 'https://www.zomato.com/lucknow/mocha-gomti-nagar/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_1_restaurant_menu_url': 'https://www.zomato.com/lucknow/mocha-gomti-nagar/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_1_restaurant_featured_image': 'https://b.zmtcdn.com/data/pictures/0/801690/fa778a9be95f95e7d9846e23b59c8d1a_featured_v2.jpg',
    'restaurants_1_restaurant_has_online_delivery': 0,
    'restaurants_1_restaurant_is_delivering_now': 0,
    'restaurants_1_restaurant_deeplink': 'zomato://restaurant/801690',
    'restaurants_1_restaurant_has_table_booking': 0,
    'restaurants_1_restaurant_events_url': 'https://www.zomato.com/lucknow/mocha-gomti-nagar/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_2_restaurant_R_res_id': 17558738,
    'restaurants_2_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_2_restaurant_id': '17558738',
    'restaurants_2_restaurant_name': 'Blue House Cafe',
    'restaurants_2_restaurant_url': 'https://www.zomato.com/vernonia-or/blue-house-cafe-vernonia?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_2_restaurant_location_address': '919 Bridge St, Vernonia, OR 97064',
    'restaurants_2_restaurant_location_locality': 'Vernonia',
    'restaurants_2_restaurant_location_city': 'Vernonia',
    'restaurants_2_restaurant_location_city_id': 8351,
    'restaurants_2_restaurant_location_latitude': '45.8586670000',
    'restaurants_2_restaurant_location_longitude': '-123.1954368000',
    'restaurants_2_restaurant_location_zipcode': '97064',
    'restaurants_2_restaurant_location_country_id': 216,
    'restaurants_2_restaurant_location_locality_verbose': 'Vernonia, Vernonia',
    'restaurants_2_restaurant_switch_to_order_menu': 0,
    'restaurants_2_restaurant_cuisines': 'Coffee and Tea, Mediterranean',
    'restaurants_2_restaurant_average_cost_for_two': 10,
    'restaurants_2_restaurant_price_range': 1,
    'restaurants_2_restaurant_currency': '$',
    'restaurants_2_restaurant_thumb': '',
    'restaurants_2_restaurant_user_rating_aggregate_rating': '4.3',
    'restaurants_2_restaurant_user_rating_rating_text': 'Very Good',
    'restaurants_2_restaurant_user_rating_rating_color': '5BA829',
    'restaurants_2_restaurant_user_rating_votes': '88',
    'restaurants_2_restaurant_photos_url': 'https://www.zomato.com/vernonia-or/blue-house-cafe-vernonia/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_2_restaurant_menu_url': 'https://www.zomato.com/vernonia-or/blue-house-cafe-vernonia/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_2_restaurant_featured_image': '',
    'restaurants_2_restaurant_has_online_delivery': 0,
    'restaurants_2_restaurant_is_delivering_now': 0,
    'restaurants_2_restaurant_deeplink': 'zomato://restaurant/17558738',
    'restaurants_2_restaurant_has_table_booking': 0,
    'restaurants_2_restaurant_events_url': 'https://www.zomato.com/vernonia-or/blue-house-cafe-vernonia/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_3_restaurant_R_res_id': 16611701,
    'restaurants_3_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_3_restaurant_id': '16611701',
    'restaurants_3_restaurant_name': 'Star Buffet',
    'restaurants_3_restaurant_url': 'https://www.zomato.com/mayfield-nsw/star-buffet-mayfield?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_3_restaurant_location_address': '58 Hanbury St, Mayfield, NSW',
    'restaurants_3_restaurant_location_locality': 'Mayfield',
    'restaurants_3_restaurant_location_city': 'Mayfield',
    'restaurants_3_restaurant_location_city_id': 2249,
    'restaurants_3_restaurant_location_latitude': '-32.8991780000',
    'restaurants_3_restaurant_location_longitude': '151.7343832000',
    'restaurants_3_restaurant_location_zipcode': '2304',
    'restaurants_3_restaurant_location_country_id': 14,
    'restaurants_3_restaurant_location_locality_verbose': 'Mayfield, Mayfield',
    'restaurants_3_restaurant_switch_to_order_menu': 0,
    'restaurants_3_restaurant_cuisines': 'Asian',
    'restaurants_3_restaurant_average_cost_for_two': 20,
    'restaurants_3_restaurant_price_range': 2,
    'restaurants_3_restaurant_currency': '$',
    'restaurants_3_restaurant_thumb': '',
    'restaurants_3_restaurant_user_rating_aggregate_rating': '2.9',
    'restaurants_3_restaurant_user_rating_rating_text': 'Average',
    'restaurants_3_restaurant_user_rating_rating_color': 'FFBA00',
    'restaurants_3_restaurant_user_rating_votes': '11',
    'restaurants_3_restaurant_photos_url': 'https://www.zomato.com/mayfield-nsw/star-buffet-mayfield/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_3_restaurant_menu_url': 'https://www.zomato.com/mayfield-nsw/star-buffet-mayfield/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_3_restaurant_featured_image': '',
    'restaurants_3_restaurant_has_online_delivery': 0,
    'restaurants_3_restaurant_is_delivering_now': 0,
    'restaurants_3_restaurant_deeplink': 'zomato://restaurant/16611701',
    'restaurants_3_restaurant_has_table_booking': 0,
    'restaurants_3_restaurant_events_url': 'https://www.zomato.com/mayfield-nsw/star-buffet-mayfield/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_4_restaurant_R_res_id': 2100784,
    'restaurants_4_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_4_restaurant_id': '2100784',
    'restaurants_4_restaurant_name': '11th Avenue Cafe Bistro',
    'restaurants_4_restaurant_url': 'https://www.zomato.com/guwahati/11th-avenue-cafe-bistro-uzan-bazaar?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_4_restaurant_location_address': 'Opposite Assam State Museum, Dighalipukhuri, Tayabullah Road, Uzan Bazaar, Guwahati',
    'restaurants_4_restaurant_location_locality': 'Uzan Bazaar',
    'restaurants_4_restaurant_location_city': 'Guwahati',
    'restaurants_4_restaurant_location_city_id': 21,
    'restaurants_4_restaurant_location_latitude': '26.1860014826',
    'restaurants_4_restaurant_location_longitude': '91.7523143068',
    'restaurants_4_restaurant_location_zipcode': '',
    'restaurants_4_restaurant_location_country_id': 1,
    'restaurants_4_restaurant_location_locality_verbose': 'Uzan Bazaar, Guwahati',
    'restaurants_4_restaurant_switch_to_order_menu': 0,
    'restaurants_4_restaurant_cuisines': 'Cafe, American, Italian, Continental',
    'restaurants_4_restaurant_average_cost_for_two': 400,
    'restaurants_4_restaurant_price_range': 2,
    'restaurants_4_restaurant_currency': 'Rs.',
    'restaurants_4_restaurant_thumb': 'https://b.zmtcdn.com/data/pictures/4/2100784/860f3b37ed3b2f15dce83c95577c07a0_featured_v2.jpg',
    'restaurants_4_restaurant_user_rating_aggregate_rating': '4.1',
    'restaurants_4_restaurant_user_rating_rating_text': 'Very Good',
    'restaurants_4_restaurant_user_rating_rating_color': '5BA829',
    'restaurants_4_restaurant_user_rating_votes': '377',
    'restaurants_4_restaurant_photos_url': 'https://www.zomato.com/guwahati/11th-avenue-cafe-bistro-uzan-bazaar/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_4_restaurant_menu_url': 'https://www.zomato.com/guwahati/11th-avenue-cafe-bistro-uzan-bazaar/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_4_restaurant_featured_image': 'https://b.zmtcdn.com/data/pictures/4/2100784/860f3b37ed3b2f15dce83c95577c07a0_featured_v2.jpg',
    'restaurants_4_restaurant_has_online_delivery': 0,
    'restaurants_4_restaurant_is_delivering_now': 0,
    'restaurants_4_restaurant_deeplink': 'zomato://restaurant/2100784',
    'restaurants_4_restaurant_has_table_booking': 0,
    'restaurants_4_restaurant_events_url': 'https://www.zomato.com/guwahati/11th-avenue-cafe-bistro-uzan-bazaar/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_5_restaurant_R_res_id': 801269,
    'restaurants_5_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_5_restaurant_id': '801269',
    'restaurants_5_restaurant_name': 'Vintage Machine',
    'restaurants_5_restaurant_url': 'https://www.zomato.com/lucknow/vintage-machine-gomti-nagar?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_5_restaurant_location_address': '3/11 Patrakar Puram, Gomti Nagar, Lucknow',
    'restaurants_5_restaurant_location_locality': 'Gomti Nagar',
    'restaurants_5_restaurant_location_city': 'Lucknow',
    'restaurants_5_restaurant_location_city_id': 8,
    'restaurants_5_restaurant_location_latitude': '26.8536376008',
    'restaurants_5_restaurant_location_longitude': '81.0004396542',
    'restaurants_5_restaurant_location_zipcode': '226010',
    'restaurants_5_restaurant_location_country_id': 1,
    'restaurants_5_restaurant_location_locality_verbose': 'Gomti Nagar, Lucknow',
    'restaurants_5_restaurant_switch_to_order_menu': 0,
    'restaurants_5_restaurant_cuisines': 'Italian, American, Lebanese',
    'restaurants_5_restaurant_average_cost_for_two': 1000,
    'restaurants_5_restaurant_price_range': 3,
    'restaurants_5_restaurant_currency': 'Rs.',
    'restaurants_5_restaurant_thumb': 'https://b.zmtcdn.com/data/pictures/9/801269/86ca93f9174f778e58d2f61858c4f4a7_featured_v2.jpg',
    'restaurants_5_restaurant_user_rating_aggregate_rating': '4.3',
    'restaurants_5_restaurant_user_rating_rating_text': 'Very Good',
    'restaurants_5_restaurant_user_rating_rating_color': '5BA829',
    'restaurants_5_restaurant_user_rating_votes': '887',
    'restaurants_5_restaurant_photos_url': 'https://www.zomato.com/lucknow/vintage-machine-gomti-nagar/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_5_restaurant_menu_url': 'https://www.zomato.com/lucknow/vintage-machine-gomti-nagar/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_5_restaurant_featured_image': 'https://b.zmtcdn.com/data/pictures/9/801269/86ca93f9174f778e58d2f61858c4f4a7_featured_v2.jpg',
    'restaurants_5_restaurant_has_online_delivery': 0,
    'restaurants_5_restaurant_is_delivering_now': 0,
    'restaurants_5_restaurant_deeplink': 'zomato://restaurant/801269',
    'restaurants_5_restaurant_has_table_booking': 0,
    'restaurants_5_restaurant_events_url': 'https://www.zomato.com/lucknow/vintage-machine-gomti-nagar/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_6_restaurant_R_res_id': 18483082,
    'restaurants_6_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_6_restaurant_id': '18483082',
    'restaurants_6_restaurant_name': 'Artistry',
    'restaurants_6_restaurant_url': 'https://www.zomato.com/singapore/artistry-rochor?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_6_restaurant_location_address': '17 Jalan Pinang 199149',
    'restaurants_6_restaurant_location_locality': 'Sungai Pinang, Rochor',
    'restaurants_6_restaurant_location_city': 'Singapore',
    'restaurants_6_restaurant_location_city_id': 52,
    'restaurants_6_restaurant_location_latitude': '1.3030346478',
    'restaurants_6_restaurant_location_longitude': '103.8581812550',
    'restaurants_6_restaurant_location_zipcode': '199149',
    'restaurants_6_restaurant_location_country_id': 184,
    'restaurants_6_restaurant_location_locality_verbose': 'Sungai Pinang, Rochor, Singapore',
    'restaurants_6_restaurant_switch_to_order_menu': 0,
    'restaurants_6_restaurant_cuisines': 'American, Bakery, European, Burger, Fusion',
    'restaurants_6_restaurant_average_cost_for_two': 50,
    'restaurants_6_restaurant_price_range': 3,
    'restaurants_6_restaurant_currency': '$',
    'restaurants_6_restaurant_thumb': 'https://b.zmtcdn.com/data/pictures/2/18483082/094ba8f9c393f945de6388e24f173633_featured_v2.jpg',
    'restaurants_6_restaurant_user_rating_aggregate_rating': '3.8',
    'restaurants_6_restaurant_user_rating_rating_text': 'Good',
    'restaurants_6_restaurant_user_rating_rating_color': '9ACD32',
    'restaurants_6_restaurant_user_rating_votes': '28',
    'restaurants_6_restaurant_photos_url': 'https://www.zomato.com/singapore/artistry-rochor/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_6_restaurant_menu_url': 'https://www.zomato.com/singapore/artistry-rochor/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_6_restaurant_featured_image': 'https://b.zmtcdn.com/data/pictures/2/18483082/094ba8f9c393f945de6388e24f173633_featured_v2.jpg',
    'restaurants_6_restaurant_has_online_delivery': 0,
    'restaurants_6_restaurant_is_delivering_now': 0,
    'restaurants_6_restaurant_deeplink': 'zomato://restaurant/18483082',
    'restaurants_6_restaurant_has_table_booking': 0,
    'restaurants_6_restaurant_events_url': 'https://www.zomato.com/singapore/artistry-rochor/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_7_restaurant_R_res_id': 18483252,
    'restaurants_7_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_7_restaurant_id': '18483252',
    'restaurants_7_restaurant_name': 'Artichoke Cafe',
    'restaurants_7_restaurant_url': 'https://www.zomato.com/singapore/artichoke-cafe-rochor?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_7_restaurant_location_address': '161 Middle Road, Sculpture Square 188978',
    'restaurants_7_restaurant_location_locality': 'Victoria, Rochor',
    'restaurants_7_restaurant_location_city': 'Singapore',
    'restaurants_7_restaurant_location_city_id': 52,
    'restaurants_7_restaurant_location_latitude': '1.2997077261',
    'restaurants_7_restaurant_location_longitude': '103.8519942920',
    'restaurants_7_restaurant_location_zipcode': '188978',
    'restaurants_7_restaurant_location_country_id': 184,
    'restaurants_7_restaurant_location_locality_verbose': 'Victoria, Rochor, Singapore',
    'restaurants_7_restaurant_switch_to_order_menu': 0,
    'restaurants_7_restaurant_cuisines': 'Cafe, Spanish, Turkish, Greek',
    'restaurants_7_restaurant_average_cost_for_two': 75,
    'restaurants_7_restaurant_price_range': 4,
    'restaurants_7_restaurant_currency': '$',
    'restaurants_7_restaurant_thumb': 'https://b.zmtcdn.com/data/pictures/2/18483252/91b2817c08b3696219d72fb9302277cc_featured_v2.jpg',
    'restaurants_7_restaurant_user_rating_aggregate_rating': '3.2',
    'restaurants_7_restaurant_user_rating_rating_text': 'Average',
    'restaurants_7_restaurant_user_rating_rating_color': 'CDD614',
    'restaurants_7_restaurant_user_rating_votes': '33',
    'restaurants_7_restaurant_photos_url': 'https://www.zomato.com/singapore/artichoke-cafe-rochor/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_7_restaurant_menu_url': 'https://www.zomato.com/singapore/artichoke-cafe-rochor/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_7_restaurant_featured_image': 'https://b.zmtcdn.com/data/pictures/2/18483252/91b2817c08b3696219d72fb9302277cc_featured_v2.jpg',
    'restaurants_7_restaurant_has_online_delivery': 0,
    'restaurants_7_restaurant_is_delivering_now': 0,
    'restaurants_7_restaurant_deeplink': 'zomato://restaurant/18483252',
    'restaurants_7_restaurant_has_table_booking': 0,
    'restaurants_7_restaurant_events_url': 'https://www.zomato.com/singapore/artichoke-cafe-rochor/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_8_restaurant_R_res_id': 16615894,
    'restaurants_8_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_8_restaurant_id': '16615894',
    'restaurants_8_restaurant_name': 'The Giggling Goat',
    'restaurants_8_restaurant_url': 'https://www.zomato.com/dicky-beach-qld/the-giggling-goat-dicky-beach?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_8_restaurant_location_address': '14 Beerburrum St, Dicky Beach, QLD',
    'restaurants_8_restaurant_location_locality': 'Dicky Beach',
    'restaurants_8_restaurant_location_city': 'Dicky Beach',
    'restaurants_8_restaurant_location_city_id': 2575,
    'restaurants_8_restaurant_location_latitude': '-26.7835760000',
    'restaurants_8_restaurant_location_longitude': '153.1374010000',
    'restaurants_8_restaurant_location_zipcode': '4551',
    'restaurants_8_restaurant_location_country_id': 14,
    'restaurants_8_restaurant_location_locality_verbose': 'Dicky Beach, Dicky Beach',
    'restaurants_8_restaurant_switch_to_order_menu': 0,
    'restaurants_8_restaurant_cuisines': 'Coffee and Tea, Tea, Modern Australian',
    'restaurants_8_restaurant_average_cost_for_two': 7,
    'restaurants_8_restaurant_price_range': 1,
    'restaurants_8_restaurant_currency': '$',
    'restaurants_8_restaurant_thumb': '',
    'restaurants_8_restaurant_user_rating_aggregate_rating': '3.6',
    'restaurants_8_restaurant_user_rating_rating_text': 'Good',
    'restaurants_8_restaurant_user_rating_rating_color': '9ACD32',
    'restaurants_8_restaurant_user_rating_votes': '29',
    'restaurants_8_restaurant_photos_url': 'https://www.zomato.com/dicky-beach-qld/the-giggling-goat-dicky-beach/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_8_restaurant_menu_url': 'https://www.zomato.com/dicky-beach-qld/the-giggling-goat-dicky-beach/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_8_restaurant_featured_image': '',
    'restaurants_8_restaurant_has_online_delivery': 0,
    'restaurants_8_restaurant_is_delivering_now': 0,
    'restaurants_8_restaurant_deeplink': 'zomato://restaurant/16615894',
    'restaurants_8_restaurant_has_table_booking': 0,
    'restaurants_8_restaurant_events_url': 'https://www.zomato.com/dicky-beach-qld/the-giggling-goat-dicky-beach/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_9_restaurant_R_res_id': 16605194,
    'restaurants_9_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_9_restaurant_id': '16605194',
    'restaurants_9_restaurant_name': 'Pig and Whistle',
    'restaurants_9_restaurant_url': 'https://www.zomato.com/trentham-east-vic/pig-and-whistle-trentham-east?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_9_restaurant_location_address': 'Pearsons Rd, Trentham East, VIC',
    'restaurants_9_restaurant_location_locality': 'Trentham East',
    'restaurants_9_restaurant_location_city': 'Trentham East',
    'restaurants_9_restaurant_location_city_id': 1556,
    'restaurants_9_restaurant_location_latitude': '-37.3969420000',
    'restaurants_9_restaurant_location_longitude': '144.4127200000',
    'restaurants_9_restaurant_location_zipcode': '3458',
    'restaurants_9_restaurant_location_country_id': 14,
    'restaurants_9_restaurant_location_locality_verbose': 'Trentham East, Trentham East',
    'restaurants_9_restaurant_switch_to_order_menu': 0,
    'restaurants_9_restaurant_cuisines': 'Australian',
    'restaurants_9_restaurant_average_cost_for_two': 20,
    'restaurants_9_restaurant_price_range': 2,
    'restaurants_9_restaurant_currency': '$',
    'restaurants_9_restaurant_thumb': '',
    'restaurants_9_restaurant_user_rating_aggregate_rating': '4.1',
    'restaurants_9_restaurant_user_rating_rating_text': 'Very Good',
    'restaurants_9_restaurant_user_rating_rating_color': '5BA829',
    'restaurants_9_restaurant_user_rating_votes': '87',
    'restaurants_9_restaurant_photos_url': 'https://www.zomato.com/trentham-east-vic/pig-and-whistle-trentham-east/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_9_restaurant_menu_url': 'https://www.zomato.com/trentham-east-vic/pig-and-whistle-trentham-east/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_9_restaurant_featured_image': '',
    'restaurants_9_restaurant_has_online_delivery': 0,
    'restaurants_9_restaurant_is_delivering_now': 0,
    'restaurants_9_restaurant_deeplink': 'zomato://restaurant/16605194',
    'restaurants_9_restaurant_has_table_booking': 0,
    'restaurants_9_restaurant_events_url': 'https://www.zomato.com/trentham-east-vic/pig-and-whistle-trentham-east/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_10_restaurant_R_res_id': 16605794,
    'restaurants_10_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_10_restaurant_id': '16605794',
    'restaurants_10_restaurant_name': 'Funkey Monkey',
    'restaurants_10_restaurant_url': 'https://www.zomato.com/lakes-entrance-vic/funkey-monkey-lakes-entrance?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_10_restaurant_location_address': '26 Myer street, Lakes Entrance, VIC',
    'restaurants_10_restaurant_location_locality': 'Lakes Entrance',
    'restaurants_10_restaurant_location_city': 'Lakes Entrance',
    'restaurants_10_restaurant_location_city_id': 1364,
    'restaurants_10_restaurant_location_latitude': '-37.8783865000',
    'restaurants_10_restaurant_location_longitude': '147.9942247000',
    'restaurants_10_restaurant_location_zipcode': '3909',
    'restaurants_10_restaurant_location_country_id': 14,
    'restaurants_10_restaurant_location_locality_verbose': 'Lakes Entrance, Lakes Entrance',
    'restaurants_10_restaurant_switch_to_order_menu': 0,
    'restaurants_10_restaurant_cuisines': 'Breakfast, Coffee and Tea',
    'restaurants_10_restaurant_average_cost_for_two': 7,
    'restaurants_10_restaurant_price_range': 1,
    'restaurants_10_restaurant_currency': '$',
    'restaurants_10_restaurant_thumb': '',
    'restaurants_10_restaurant_user_rating_aggregate_rating': '3.8',
    'restaurants_10_restaurant_user_rating_rating_text': 'Good',
    'restaurants_10_restaurant_user_rating_rating_color': '9ACD32',
    'restaurants_10_restaurant_user_rating_votes': '97',
    'restaurants_10_restaurant_photos_url': 'https://www.zomato.com/lakes-entrance-vic/funkey-monkey-lakes-entrance/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_10_restaurant_menu_url': 'https://www.zomato.com/lakes-entrance-vic/funkey-monkey-lakes-entrance/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_10_restaurant_featured_image': '',
    'restaurants_10_restaurant_has_online_delivery': 0,
    'restaurants_10_restaurant_is_delivering_now': 0,
    'restaurants_10_restaurant_deeplink': 'zomato://restaurant/16605794',
    'restaurants_10_restaurant_has_table_booking': 0,
    'restaurants_10_restaurant_events_url': 'https://www.zomato.com/lakes-entrance-vic/funkey-monkey-lakes-entrance/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_11_restaurant_R_res_id': 16604358,
    'restaurants_11_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_11_restaurant_id': '16604358',
    'restaurants_11_restaurant_name': 'Blue Bean Love Cafe',
    'restaurants_11_restaurant_url': 'https://www.zomato.com/hepburn-springs-vic/blue-bean-love-cafe-hepburn-springs?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_11_restaurant_location_address': '115 Main Rd, Hepburn Springs, Hepburn Springs, VIC',
    'restaurants_11_restaurant_location_locality': 'Hepburn Springs',
    'restaurants_11_restaurant_location_city': 'Hepburn Springs',
    'restaurants_11_restaurant_location_city_id': 1563,
    'restaurants_11_restaurant_location_latitude': '-37.3123267000',
    'restaurants_11_restaurant_location_longitude': '144.1387014000',
    'restaurants_11_restaurant_location_zipcode': '3461',
    'restaurants_11_restaurant_location_country_id': 14,
    'restaurants_11_restaurant_location_locality_verbose': 'Hepburn Springs, Hepburn Springs',
    'restaurants_11_restaurant_switch_to_order_menu': 0,
    'restaurants_11_restaurant_cuisines': 'Cafe, Coffee and Tea, Modern Australian',
    'restaurants_11_restaurant_average_cost_for_two': 20,
    'restaurants_11_restaurant_price_range': 2,
    'restaurants_11_restaurant_currency': '$',
    'restaurants_11_restaurant_thumb': '',
    'restaurants_11_restaurant_user_rating_aggregate_rating': '3.8',
    'restaurants_11_restaurant_user_rating_rating_text': 'Good',
    'restaurants_11_restaurant_user_rating_rating_color': '9ACD32',
    'restaurants_11_restaurant_user_rating_votes': '192',
    'restaurants_11_restaurant_photos_url': 'https://www.zomato.com/hepburn-springs-vic/blue-bean-love-cafe-hepburn-springs/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_11_restaurant_menu_url': 'https://www.zomato.com/hepburn-springs-vic/blue-bean-love-cafe-hepburn-springs/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_11_restaurant_featured_image': '',
    'restaurants_11_restaurant_has_online_delivery': 0,
    'restaurants_11_restaurant_is_delivering_now': 0,
    'restaurants_11_restaurant_deeplink': 'zomato://restaurant/16604358',
    'restaurants_11_restaurant_has_table_booking': 0,
    'restaurants_11_restaurant_events_url': 'https://www.zomato.com/hepburn-springs-vic/blue-bean-love-cafe-hepburn-springs/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_12_restaurant_R_res_id': 17534788,
    'restaurants_12_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_12_restaurant_id': '17534788',
    'restaurants_12_restaurant_name': 'The Artesian Restaurant',
    'restaurants_12_restaurant_url': 'https://www.zomato.com/ojo-caliente-nm/the-artesian-restaurant-ojo-caliente?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_12_restaurant_location_address': 'Ojo Caliente Mineral Springs Resort And Spa 50 Los Banos Rd, Ojo Caliente, NM 87549',
    'restaurants_12_restaurant_location_locality': 'Ojo Caliente',
    'restaurants_12_restaurant_location_city': 'Ojo Caliente',
    'restaurants_12_restaurant_location_city_id': 7598,
    'restaurants_12_restaurant_location_latitude': '36.3136380000',
    'restaurants_12_restaurant_location_longitude': '-106.0576660000',
    'restaurants_12_restaurant_location_zipcode': '87549',
    'restaurants_12_restaurant_location_country_id': 216,
    'restaurants_12_restaurant_location_locality_verbose': 'Ojo Caliente, Ojo Caliente',
    'restaurants_12_restaurant_switch_to_order_menu': 0,
    'restaurants_12_restaurant_cuisines': 'American, International, Southwestern',
    'restaurants_12_restaurant_average_cost_for_two': 40,
    'restaurants_12_restaurant_price_range': 3,
    'restaurants_12_restaurant_currency': '$',
    'restaurants_12_restaurant_thumb': '',
    'restaurants_12_restaurant_user_rating_aggregate_rating': '3.6',
    'restaurants_12_restaurant_user_rating_rating_text': 'Good',
    'restaurants_12_restaurant_user_rating_rating_color': '9ACD32',
    'restaurants_12_restaurant_user_rating_votes': '30',
    'restaurants_12_restaurant_photos_url': 'https://www.zomato.com/ojo-caliente-nm/the-artesian-restaurant-ojo-caliente/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_12_restaurant_menu_url': 'https://www.zomato.com/ojo-caliente-nm/the-artesian-restaurant-ojo-caliente/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_12_restaurant_featured_image': '',
    'restaurants_12_restaurant_has_online_delivery': 0,
    'restaurants_12_restaurant_is_delivering_now': 0,
    'restaurants_12_restaurant_deeplink': 'zomato://restaurant/17534788',
    'restaurants_12_restaurant_has_table_booking': 0,
    'restaurants_12_restaurant_events_url': 'https://www.zomato.com/ojo-caliente-nm/the-artesian-restaurant-ojo-caliente/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_13_restaurant_R_res_id': 16606299,
    'restaurants_13_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_13_restaurant_id': '16606299',
    'restaurants_13_restaurant_name': 'Beach Box Cafe',
    'restaurants_13_restaurant_url': 'https://www.zomato.com/inverloch-vic/beach-box-cafe-inverloch?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_13_restaurant_location_address': '6a Ramsay Blvd, Inverloch, VIC',
    'restaurants_13_restaurant_location_locality': 'Inverloch',
    'restaurants_13_restaurant_location_city': 'Inverloch',
    'restaurants_13_restaurant_location_city_id': 1342,
    'restaurants_13_restaurant_location_latitude': '-38.6347458000',
    'restaurants_13_restaurant_location_longitude': '145.7287133000',
    'restaurants_13_restaurant_location_zipcode': '3996',
    'restaurants_13_restaurant_location_country_id': 14,
    'restaurants_13_restaurant_location_locality_verbose': 'Inverloch, Inverloch',
    'restaurants_13_restaurant_switch_to_order_menu': 0,
    'restaurants_13_restaurant_cuisines': 'Burger, Coffee and Tea, Modern Australian',
    'restaurants_13_restaurant_average_cost_for_two': 7,
    'restaurants_13_restaurant_price_range': 1,
    'restaurants_13_restaurant_currency': '$',
    'restaurants_13_restaurant_thumb': '',
    'restaurants_13_restaurant_user_rating_aggregate_rating': '3.7',
    'restaurants_13_restaurant_user_rating_rating_text': 'Good',
    'restaurants_13_restaurant_user_rating_rating_color': '9ACD32',
    'restaurants_13_restaurant_user_rating_votes': '100',
    'restaurants_13_restaurant_photos_url': 'https://www.zomato.com/inverloch-vic/beach-box-cafe-inverloch/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_13_restaurant_menu_url': 'https://www.zomato.com/inverloch-vic/beach-box-cafe-inverloch/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_13_restaurant_featured_image': '',
    'restaurants_13_restaurant_has_online_delivery': 0,
    'restaurants_13_restaurant_is_delivering_now': 0,
    'restaurants_13_restaurant_deeplink': 'zomato://restaurant/16606299',
    'restaurants_13_restaurant_has_table_booking': 0,
    'restaurants_13_restaurant_events_url': 'https://www.zomato.com/inverloch-vic/beach-box-cafe-inverloch/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_14_restaurant_R_res_id': 16654702,
    'restaurants_14_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_14_restaurant_id': '16654702',
    'restaurants_14_restaurant_name': 'Lake House Restaurant',
    'restaurants_14_restaurant_url': 'https://www.zomato.com/vineland-station-on/lake-house-restaurant-vineland-station?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_14_restaurant_location_address': '3100 N Service Rd, Vineland Station, ON L0R2E0',
    'restaurants_14_restaurant_location_locality': 'Vineland Station',
    'restaurants_14_restaurant_location_city': 'Vineland Station',
    'restaurants_14_restaurant_location_city_id': 3418,
    'restaurants_14_restaurant_location_latitude': '43.1868697000',
    'restaurants_14_restaurant_location_longitude': '-79.3791465000',
    'restaurants_14_restaurant_location_zipcode': 'L0R2E0',
    'restaurants_14_restaurant_location_country_id': 37,
    'restaurants_14_restaurant_location_locality_verbose': 'Vineland Station, Vineland Station',
    'restaurants_14_restaurant_switch_to_order_menu': 0,
    'restaurants_14_restaurant_cuisines': 'Italian, Mediterranean, Pizza',
    'restaurants_14_restaurant_average_cost_for_two': 70,
    'restaurants_14_restaurant_price_range': 4,
    'restaurants_14_restaurant_currency': '$',
    'restaurants_14_restaurant_thumb': '',
    'restaurants_14_restaurant_user_rating_aggregate_rating': '4.3',
    'restaurants_14_restaurant_user_rating_rating_text': 'Very Good',
    'restaurants_14_restaurant_user_rating_rating_color': '5BA829',
    'restaurants_14_restaurant_user_rating_votes': '204',
    'restaurants_14_restaurant_photos_url': 'https://www.zomato.com/vineland-station-on/lake-house-restaurant-vineland-station/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_14_restaurant_menu_url': 'https://www.zomato.com/vineland-station-on/lake-house-restaurant-vineland-station/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_14_restaurant_featured_image': '',
    'restaurants_14_restaurant_has_online_delivery': 0,
    'restaurants_14_restaurant_is_delivering_now': 0,
    'restaurants_14_restaurant_deeplink': 'zomato://restaurant/16654702',
    'restaurants_14_restaurant_has_table_booking': 0,
    'restaurants_14_restaurant_events_url': 'https://www.zomato.com/vineland-station-on/lake-house-restaurant-vineland-station/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_15_restaurant_R_res_id': 17694056,
    'restaurants_15_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_15_restaurant_id': '17694056',
    'restaurants_15_restaurant_name': "Theo Yianni's Authentic Greek Restaurant",
    'restaurants_15_restaurant_url': 'https://www.zomato.com/weirton-wv/theo-yiannis-authentic-greek-restaurant-weirton?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_15_restaurant_location_address': '322 American Way, Weirton, WV 26062',
    'restaurants_15_restaurant_location_locality': 'Weirton',
    'restaurants_15_restaurant_location_city': 'Weirton',
    'restaurants_15_restaurant_location_city_id': 10358,
    'restaurants_15_restaurant_location_latitude': '40.3960430000',
    'restaurants_15_restaurant_location_longitude': '-80.5294880000',
    'restaurants_15_restaurant_location_zipcode': '26062',
    'restaurants_15_restaurant_location_country_id': 216,
    'restaurants_15_restaurant_location_locality_verbose': 'Weirton, Weirton',
    'restaurants_15_restaurant_switch_to_order_menu': 0,
    'restaurants_15_restaurant_cuisines': 'Burger, Greek, Sandwich',
    'restaurants_15_restaurant_average_cost_for_two': 25,
    'restaurants_15_restaurant_price_range': 2,
    'restaurants_15_restaurant_currency': '$',
    'restaurants_15_restaurant_thumb': '',
    'restaurants_15_restaurant_user_rating_aggregate_rating': '3.9',
    'restaurants_15_restaurant_user_rating_rating_text': 'Good',
    'restaurants_15_restaurant_user_rating_rating_color': '9ACD32',
    'restaurants_15_restaurant_user_rating_votes': '156',
    'restaurants_15_restaurant_photos_url': 'https://www.zomato.com/weirton-wv/theo-yiannis-authentic-greek-restaurant-weirton/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_15_restaurant_menu_url': 'https://www.zomato.com/weirton-wv/theo-yiannis-authentic-greek-restaurant-weirton/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_15_restaurant_featured_image': '',
    'restaurants_15_restaurant_has_online_delivery': 0,
    'restaurants_15_restaurant_is_delivering_now': 0,
    'restaurants_15_restaurant_deeplink': 'zomato://restaurant/17694056',
    'restaurants_15_restaurant_has_table_booking': 0,
    'restaurants_15_restaurant_events_url': 'https://www.zomato.com/weirton-wv/theo-yiannis-authentic-greek-restaurant-weirton/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_16_restaurant_R_res_id': 3700050,
    'restaurants_16_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_16_restaurant_id': '3700050',
    'restaurants_16_restaurant_name': 'Baker Street',
    'restaurants_16_restaurant_url': 'https://www.zomato.com/puducherry/baker-street-mg-road?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_16_restaurant_location_address': '123, Bussy Street, MG Road, Puducherry',
    'restaurants_16_restaurant_location_locality': 'MG Road',
    'restaurants_16_restaurant_location_city': 'Puducherry',
    'restaurants_16_restaurant_location_city_id': 37,
    'restaurants_16_restaurant_location_latitude': '11.9292750000',
    'restaurants_16_restaurant_location_longitude': '79.8295840000',
    'restaurants_16_restaurant_location_zipcode': '',
    'restaurants_16_restaurant_location_country_id': 1,
    'restaurants_16_restaurant_location_locality_verbose': 'MG Road, Puducherry',
    'restaurants_16_restaurant_switch_to_order_menu': 0,
    'restaurants_16_restaurant_cuisines': 'Bakery, French',
    'restaurants_16_restaurant_average_cost_for_two': 400,
    'restaurants_16_restaurant_price_range': 2,
    'restaurants_16_restaurant_currency': 'Rs.',
    'restaurants_16_restaurant_thumb': 'https://b.zmtcdn.com/data/pictures/0/3700050/1c47128f7b7ad012a7375f9c426d1f71_featured_v2.jpg',
    'restaurants_16_restaurant_user_rating_aggregate_rating': '4.1',
    'restaurants_16_restaurant_user_rating_rating_text': 'Very Good',
    'restaurants_16_restaurant_user_rating_rating_color': '5BA829',
    'restaurants_16_restaurant_user_rating_votes': '791',
    'restaurants_16_restaurant_photos_url': 'https://www.zomato.com/puducherry/baker-street-mg-road/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_16_restaurant_menu_url': 'https://www.zomato.com/puducherry/baker-street-mg-road/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_16_restaurant_featured_image': 'https://b.zmtcdn.com/data/pictures/0/3700050/1c47128f7b7ad012a7375f9c426d1f71_featured_v2.jpg',
    'restaurants_16_restaurant_has_online_delivery': 0,
    'restaurants_16_restaurant_is_delivering_now': 0,
    'restaurants_16_restaurant_deeplink': 'zomato://restaurant/3700050',
    'restaurants_16_restaurant_has_table_booking': 0,
    'restaurants_16_restaurant_events_url': 'https://www.zomato.com/puducherry/baker-street-mg-road/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_17_restaurant_R_res_id': 17629582,
    'restaurants_17_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_17_restaurant_id': '17629582',
    'restaurants_17_restaurant_name': 'Barrett Junction Cafe',
    'restaurants_17_restaurant_url': 'https://www.zomato.com/potrero-ca/barrett-junction-cafe-dulzura?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_17_restaurant_location_address': '1020 Barrett Lake Rd, Dulzura, CA 91917',
    'restaurants_17_restaurant_location_locality': 'Potrero',
    'restaurants_17_restaurant_location_city': 'Potrero',
    'restaurants_17_restaurant_location_city_id': 8956,
    'restaurants_17_restaurant_location_latitude': '32.6134310000',
    'restaurants_17_restaurant_location_longitude': '-116.7047310000',
    'restaurants_17_restaurant_location_zipcode': '91917',
    'restaurants_17_restaurant_location_country_id': 216,
    'restaurants_17_restaurant_location_locality_verbose': 'Potrero, Potrero',
    'restaurants_17_restaurant_switch_to_order_menu': 0,
    'restaurants_17_restaurant_cuisines': 'American, BBQ, Burger',
    'restaurants_17_restaurant_average_cost_for_two': 25,
    'restaurants_17_restaurant_price_range': 2,
    'restaurants_17_restaurant_currency': '$',
    'restaurants_17_restaurant_thumb': '',
    'restaurants_17_restaurant_user_rating_aggregate_rating': '3.3',
    'restaurants_17_restaurant_user_rating_rating_text': 'Average',
    'restaurants_17_restaurant_user_rating_rating_color': 'CDD614',
    'restaurants_17_restaurant_user_rating_votes': '9',
    'restaurants_17_restaurant_photos_url': 'https://www.zomato.com/potrero-ca/barrett-junction-cafe-dulzura/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_17_restaurant_menu_url': 'https://www.zomato.com/potrero-ca/barrett-junction-cafe-dulzura/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_17_restaurant_featured_image': '',
    'restaurants_17_restaurant_has_online_delivery': 0,
    'restaurants_17_restaurant_is_delivering_now': 0,
    'restaurants_17_restaurant_deeplink': 'zomato://restaurant/17629582',
    'restaurants_17_restaurant_has_table_booking': 0,
    'restaurants_17_restaurant_events_url': 'https://www.zomato.com/potrero-ca/barrett-junction-cafe-dulzura/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_18_restaurant_R_res_id': 18366580,
    'restaurants_18_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_18_restaurant_id': '18366580',
    'restaurants_18_restaurant_name': 'Sakura Sushi & Grill',
    'restaurants_18_restaurant_url': 'https://www.zomato.com/cochrane-wi/sakura-sushi-grill-cochrane?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_18_restaurant_location_address': '130 Quarry Street, Unit 20, Cochrane, AB T4C 0W5',
    'restaurants_18_restaurant_location_locality': 'Cochrane',
    'restaurants_18_restaurant_location_city': 'Cochrane',
    'restaurants_18_restaurant_location_city_id': 10261,
    'restaurants_18_restaurant_location_latitude': '51.1839340000',
    'restaurants_18_restaurant_location_longitude': '-114.4724740000',
    'restaurants_18_restaurant_location_zipcode': 'T4C 0W5',
    'restaurants_18_restaurant_location_country_id': 216,
    'restaurants_18_restaurant_location_locality_verbose': 'Cochrane, Cochrane',
    'restaurants_18_restaurant_switch_to_order_menu': 0,
    'restaurants_18_restaurant_cuisines': 'Asian, Japanese',
    'restaurants_18_restaurant_average_cost_for_two': 25,
    'restaurants_18_restaurant_price_range': 2,
    'restaurants_18_restaurant_currency': '$',
    'restaurants_18_restaurant_thumb': 'https://b.zmtcdn.com/data/pictures/0/18366580/cd4a59e33992548110a8c9e0fe050a77_featured_v2.jpg',
    'restaurants_18_restaurant_user_rating_aggregate_rating': '3.1',
    'restaurants_18_restaurant_user_rating_rating_text': 'Average',
    'restaurants_18_restaurant_user_rating_rating_color': 'CDD614',
    'restaurants_18_restaurant_user_rating_votes': '6',
    'restaurants_18_restaurant_photos_url': 'https://www.zomato.com/cochrane-wi/sakura-sushi-grill-cochrane/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_18_restaurant_menu_url': 'https://www.zomato.com/cochrane-wi/sakura-sushi-grill-cochrane/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_18_restaurant_featured_image': 'https://b.zmtcdn.com/data/pictures/0/18366580/cd4a59e33992548110a8c9e0fe050a77_featured_v2.jpg',
    'restaurants_18_restaurant_has_online_delivery': 0,
    'restaurants_18_restaurant_is_delivering_now': 0,
    'restaurants_18_restaurant_deeplink': 'zomato://restaurant/18366580',
    'restaurants_18_restaurant_has_table_booking': 0,
    'restaurants_18_restaurant_events_url': 'https://www.zomato.com/cochrane-wi/sakura-sushi-grill-cochrane/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_19_restaurant_R_res_id': 17211719,
    'restaurants_19_restaurant_apikey': '10a35f36f5898432823df42bc743c8aa',
    'restaurants_19_restaurant_id': '17211719',
    'restaurants_19_restaurant_name': 'Blue Point Grill',
    'restaurants_19_restaurant_url': 'https://www.zomato.com/princeton-nj/blue-point-grill-princeton?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
    'restaurants_19_restaurant_location_address': '258 Nassau St, Princeton, NJ 08542',
    'restaurants_19_restaurant_location_locality': 'Princeton',
    'restaurants_19_restaurant_location_city': 'Princeton',
    'restaurants_19_restaurant_location_city_id': 3977,
    'restaurants_19_restaurant_location_latitude': '40.3523850000',
    'restaurants_19_restaurant_location_longitude': '-74.6511390000',
    'restaurants_19_restaurant_location_zipcode': '08542',
    'restaurants_19_restaurant_location_country_id': 216,
    'restaurants_19_restaurant_location_locality_verbose': 'Princeton, Princeton',
    'restaurants_19_restaurant_switch_to_order_menu': 0,
    'restaurants_19_restaurant_cuisines': 'Seafood',
    'restaurants_19_restaurant_average_cost_for_two': 70,
    'restaurants_19_restaurant_price_range': 4,
    'restaurants_19_restaurant_currency': '$',
    'restaurants_19_restaurant_thumb': '',
    'restaurants_19_restaurant_user_rating_aggregate_rating': '4.0',
    'restaurants_19_restaurant_user_rating_rating_text': 'Very Good',
    'restaurants_19_restaurant_user_rating_rating_color': '5BA829',
    'restaurants_19_restaurant_user_rating_votes': '542',
    'restaurants_19_restaurant_photos_url': 'https://www.zomato.com/princeton-nj/blue-point-grill-princeton/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
    'restaurants_19_restaurant_menu_url': 'https://www.zomato.com/princeton-nj/blue-point-grill-princeton/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
    'restaurants_19_restaurant_featured_image': '',
    'restaurants_19_restaurant_has_online_delivery': 0,
    'restaurants_19_restaurant_is_delivering_now': 0,
    'restaurants_19_restaurant_deeplink': 'zomato://restaurant/17211719',
    'restaurants_19_restaurant_has_table_booking': 0,
    'restaurants_19_restaurant_events_url': 'https://www.zomato.com/princeton-nj/blue-point-grill-princeton/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1'
}
